CREATE DATABASE FERNANDESELDA;

GO

USE FERNANDESELDA;

CREATE TABLE Cliente(
	IDCliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome varchar(50) NOT NULL,
	NIF varchar(20) NOT NULL,
	Telefone varchar(14) NOT NULL,
	Morada varchar(100) NOT NULL,
	Email varchar(50) NULL);

CREATE TABLE Loja(
	IDLoja INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome varchar(50) NOT NULL,
	Morada varchar(100) NOT NULL);

CREATE TABLE Fornecedor(
	IDFornecedor INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome varchar(50) NOT NULL,
	NIF varchar(20) NOT NULL,
	Telefone varchar(14) NOT NULL,
	Morada varchar(100) NOT NULL,
	Email varchar(50) NULL);

CREATE TABLE Estado(
	IDEstado INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL);

CREATE TABLE Pedido(
	IDPedido INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDCliente INT NOT NULL,
	IDEstado INT NOT NULL,
	Descricao varchar(250) NULL,
	FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDEstado) REFERENCES Estado(IDEstado) ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE Peca(
	IDPeca INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Cor VARCHAR(10) NOT NULL,
	Tamanho VARCHAR(10) NOT NULL,
	Tecido VARCHAR(15) NOT NULL);

CREATE TABLE PecaPedido(
	IDPecaPedido INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPedido INT NOT NULL,
	IDPeca INT NOT NULL,
	Quantidade INT NOT NULL,
	FOREIGN KEY (IDPedido) REFERENCES Pedido(IDPedido) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDPeca) REFERENCES Peca(IDPeca) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE TipoArranjo(
	IDTipoArranjo INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome varchar(50) NOT NULL,
	Descricao varchar(250) NOT NULL);

CREATE TABLE Arranjo(
	IDArranjo INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDTipoArranjo INT NOT NULL,
	Duracao INT NOT NULL,
	Preco FLOAT NULL,
	FOREIGN KEY (IDTipoArranjo) REFERENCES TipoArranjo(IDTipoArranjo) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Artigo(
	IDArtigo INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(50) NOT NULL);
	
CREATE TABLE ArranjoArtigo(
	IDArranjoArtigo INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDArranjo INT NOT NULL,
	IDArtigo INT NOT NULL,
	Quantidade FLOAT NOT NULL,
	FOREIGN KEY (IDArranjo) REFERENCES Arranjo(IDArranjo) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDArtigo) REFERENCES Artigo(IDArtigo) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE ArranjoPedido(
	IDArranjoPedido INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPedido INT NOT NULL,
	IDArranjo INT NOT NULL,
	Observacoes varchar(250) NULL,
	FOREIGN KEY (IDPedido) REFERENCES Pedido(IDPedido) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDArranjo) REFERENCES Arranjo(IDArranjo) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE DocumentoVenda(
	IDDocumentoVenda INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPedido INT NOT NULL,
	IDLoja INT NOT NULL,
	IDEstado INT NOT NULL,
	FOREIGN KEY (IDPedido) REFERENCES Pedido(IDPedido) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDLoja) REFERENCES Loja(IDLoja) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDEstado) REFERENCES Estado(IDEstado) ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE DocumentoCompra(
	IDDocumentoCompra INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDFornecedor INT NOT NULL,
	IDLoja INT NOT NULL,
	FOREIGN KEY (IDFornecedor) REFERENCES Fornecedor(IDFornecedor) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDLoja) REFERENCES Loja(IDLoja) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE LinhasDocumentoCompra(
	IDLinhasDocumentoCompra INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDDocumentoCompra INT NOT NULL,
	IDArtigo INT NOT NULL,
	Quantidade FLOAT NOT NULL,
	FOREIGN KEY (IDDocumentoCompra) REFERENCES DocumentoCompra(IDDocumentoCompra) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDArtigo) REFERENCES Artigo(IDArtigo) ON DELETE CASCADE ON UPDATE CASCADE);